# ================================================================
# Settings
# ================================================================
[settings]
auto_install = false
install_before = "3d"


# ================================================================
# Tools
# ================================================================
[tools]

# Markdown
markdownlint-cli2 = "0.22"

# GitHub Actions
actionlint = "1"
shellcheck = "0.11"
"github:zizmorcore/zizmor" = "1"

# Other tools
lefthook = "2"
cspell = "9"

# Zenn CLI
pnpm = "10"


# ================================================================
# Tasks
# See: https://mise.jdx.dev/tasks/toml-tasks.html
# ================================================================

# Global
[tasks.setup]
description = "Setup tools"
run = ["mise trust -yq", "mise install", "lefthook install"]
alias = "s"

[tasks.fix]
description = "Fix all issues"
depends = ["md-fix", "gh-fix"]
alias = "f"

[tasks.check]
description = "Check for all issues"
depends = ["md-check", "gh-check", "spell-check"]
alias = "c"

[tasks.fix-and-check]
run = [{ task = "fix" }, { task = "check" }]
description = "Fix all issues and check for issues"
alias = "fc"

# Markdown
[tasks.md-fix]
description = "Fix Markdown issues"
run = "markdownlint-cli2 '**/*.md' --fix"
alias = "mf"

[tasks.md-check]
description = "Check for Markdown issues"
run = "markdownlint-cli2 '**/*.md'"
alias = "mc"

# GitHub Actions
[tasks.gh-fix]
description = "Fix GitHub Actions workflows"
run = "zizmor --fix=all ."
alias = "ghf"

[tasks.gh-check]
description = "Check GitHub Actions workflows"
run = [
  "actionlint .github/workflows/*.yml",
  "zizmor . --persona=pedantic --min-severity=medium",
]
alias = "ghc"

# Spell Check
[tasks.spell-check]
description = "Check spelling"
run = "cspell . --gitignore --verbose"
alias = "sc"

# Zenn CLI
[tasks.zenn-setup]
description = "Initialize Zenn CLI"
run = ["pnpm install --frozen-lockfile"]
alias = "zi"

[tasks.zenn-new-article]
description = "Create a new Zenn article"
run = "pnpm zenn new:article"
alias = "zna"

[tasks.zenn-preview]
description = "Preview Zenn contents"
run = "pnpm zenn preview"
alias = "zp"
